// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quizzer.Infrastructure.Persistence;

#nullable disable

namespace Quizzer.Infrastructure.Migrations
{
    [DbContext(typeof(QuizzerDbContext))]
    partial class QuizzerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("Quizzer.Domain.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExamVersionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("ScorePercent")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Attempts");
                });

            modelBuilder.Entity("Quizzer.Domain.AttemptAnswer", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("FlaggedDoubt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("QuestionKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("SecondsSpent")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SelectedOptionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SelectedOptionKey")
                        .HasColumnType("TEXT");

                    b.HasKey("AttemptId", "QuestionId");

                    b.ToTable("AttemptAnswers");
                });

            modelBuilder.Entity("Quizzer.Domain.Exams.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Quizzer.Domain.Exams.ExamVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("ExamVersions");
                });

            modelBuilder.Entity("Quizzer.Domain.Exams.Option", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OptionKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OptionKey");

                    b.HasIndex("QuestionId");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("Quizzer.Domain.Exams.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CorrectOptionId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ExamVersionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Explanation")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("QuestionKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamVersionId");

                    b.HasIndex("QuestionKey");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Quizzer.Domain.Study.QuestionStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("DueAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("EaseFactor")
                        .HasColumnType("REAL");

                    b.Property<int>("IntervalDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastCorrectAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("QuestionKey")
                        .HasColumnType("TEXT");

                    b.Property<int>("WrongCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("QuestionKey");

                    b.ToTable("QuestionStats");
                });

            modelBuilder.Entity("Quizzer.Domain.AttemptAnswer", b =>
                {
                    b.HasOne("Quizzer.Domain.Attempt", null)
                        .WithMany("Answers")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quizzer.Domain.Exams.ExamVersion", b =>
                {
                    b.HasOne("Quizzer.Domain.Exams.Exam", null)
                        .WithMany("Versions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quizzer.Domain.Exams.Option", b =>
                {
                    b.HasOne("Quizzer.Domain.Exams.Question", null)
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quizzer.Domain.Exams.Question", b =>
                {
                    b.HasOne("Quizzer.Domain.Exams.ExamVersion", null)
                        .WithMany("Questions")
                        .HasForeignKey("ExamVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Quizzer.Domain.Attempt", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("Quizzer.Domain.Exams.Exam", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Quizzer.Domain.Exams.ExamVersion", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Quizzer.Domain.Exams.Question", b =>
                {
                    b.Navigation("Options");
                });
#pragma warning restore 612, 618
        }
    }
}
